### ISSUE TITLE
🛑 Onchain Backend is down

### ISSUE THREAD

**Issue by TrimVis** [MuesliSwapLabs/uptime-monitor#12]
In [`86f192d`](https://github.com/MuesliSwapLabs/uptime-monitor/commit/86f192dceccdbb7e7408644a631492c8d627140f
), Onchain Backend (https://onchain.muesliswap.com/health) was **down**:
- HTTP code: 542
- Response time: 1557 ms

**Comment by nielstron** [comment]
the onchain orderbook does currently not guard against orders that might buy 0. such orders are usually filled by a special service call "zero_fill.py" in the matchmaking code instantly but did not run right now. We should consider guarding against orders that buy 0 anyways
